nav:
  Home: /
  About: /about/
  Writing: /archives/
  Experiments: http://github.com/xanderlewis

projects_url: http://github.com/xanderlewis

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/me-zoom.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/xanderlewis
        soundcloud: http://soundcloud.com/xander
        twitter: http://twitter.com/xndrlws
    show_all_posts: false
    post_count: 5
    highlight: monokai-sublime

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-107704067-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
